version: '3'
services: 
  api: 
    restart: always
    build: ../../.
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
     - test
    environment: 
      - dockerNetwork=web
      - gqlProxyToken=1234
      - qglProxyRuntime=dockerWatch
      - gqlProxyKnownOldSchemas=true
      - winstonLogLevel=debug
    volumes: 
     - /var/run/docker.sock:/var/run/docker.sock
networks:
  test:
    external: true